# Generated by Django 3.2 on 2021-09-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='tilte',
            new_name='title',
        ),
    ]
